#!/usr/bin/env bash
#Loops through " Best School" 10 times using while loop
#Displays "Hi" on the 9th loop

i=0

while [ $i -ge 10 ]; do
    if [ $i -eq 9 ]; then
	echo "Best School"
	echo "Hi"
    else
	echo "Best School"
    fi
   
    ((i++))
done	
